version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - riccardom
    labels:
      - automerge
      - dependencies
  - package-ecosystem: pub
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - riccardom
    labels:
      - automerge
      - dependencies
