name: qadena_alan
description: Dart library to easily integrate with Qadena.
version: 0.99.1
homepage: https://github.com/alan-sdk/alan.dart
environment:
  sdk: ^3.4.3

dependencies:
  analyzer: ^5.13.0
  asn1lib: ^1.5.6
  bech32: ^0.2.2
  bip39: ^1.0.6
  bip32: ^2.0.0
  convert: ^3.1.2
  equatable: ^2.0.5
  fixnum: ^1.1.1
  grpc: ^3.2.4
  hex: ^0.2.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  meta: ^1.15.0
  pointycastle: ^3.9.1
  protobuf: ^3.1.0
  blockchain_utils: ^3.4.0
  dart_pdf_reader: ^2.1.0
  web3dart: ^2.7.3
  elliptic: ^0.3.11
  decimal: ^3.1.0
  tuple: ^2.0.0  # Check for the latest version on pub.dev
  eciesdart:
    git:
      url: https://github.com/ecies/dart.git
      ref: main

dev_dependencies:
  build_runner: ^2.4.11
  mockito: ^5.4.4
  mock_web_server: ^5.0.0-nullsafety.1
  test: ^1.25.8
  lints: ">=2.1.1 <6.0.0"
